export const ACTION_TYPES = {
  SIGN_IN_CHANGE_EMAIL_INPUT: Symbol("SIGN_IN.CHANGE_EMAIL_INPUT"),
  SIGN_IN_CHANGE_PASSWORD_INPUT: Symbol("SIGN_IN.CHANGE_PASSWORD_INPUT"),

  SIGN_UP_CHANGE_EMAIL_INPUT: Symbol("SIGN_UP.CHANGE_EMAIL_INPUT"),
  SIGN_UP_CHANGE_PASSWORD_INPUT: Symbol("SIGN_UP.CHANGE_PASSWORD_INPUT"),
  SIGN_UP_CHANGE_REPEAT_PASSWORD_INPUT: Symbol("SIGN_UP.CHANGE_REPEAT_PASSWORD_INPUT"),

  HOME_START_TO_GET_ORDER_BOOK: Symbol("HOME.START_TO_GET_ORDER_BOOK"),
  HOME_SUCCEEDED_TO_GET_ORDER_BOOK: Symbol("HOME.SUCCEEDED_TO_GET_ORDER_BOOK"),
  HOME_FAILED_TO_GET_ORDER_BOOK: Symbol("HOME.FAILED_TO_GET_ORDER_BOOK"),

  GLOBAL_LOCATION_CHANGE: "@@router/LOCATION_CHANGE",
};
