export const ACTION_TYPES = {
  SIGN_IN_CHANGE_EMAIL_INPUT: Symbol("SIGN_IN.CHANGE_EMAIL_INPUT"),
  SIGN_IN_CHANGE_PASSWORD_INPUT: Symbol("SIGN_IN.CHANGE_PASSWORD_INPUT"),
  SIGN_IN_START_TO_GET_ACCESS_TOKEN: Symbol("SIGN_IN.START_TO_GET_ACCESS_TOKEN"),
  SIGN_IN_SUCCEEDED_TO_GET_ACCESS_TOKEN: Symbol("SIGN_IN.SUCCEEDED_TO_GET_ACCESS_TOKEN"),
  SIGN_IN_FAILED_TO_GET_ACCESS_TOKEN: Symbol("SIGN_IN.FAILED_TO_GET_ACCESS_TOKEN"),

  SIGN_UP_CHANGE_EMAIL_INPUT: Symbol("SIGN_UP.CHANGE_EMAIL_INPUT"),
  SIGN_UP_CHANGE_PASSWORD_INPUT: Symbol("SIGN_UP.CHANGE_PASSWORD_INPUT"),
  SIGN_UP_CHANGE_REPEAT_PASSWORD_INPUT: Symbol("SIGN_UP.CHANGE_REPEAT_PASSWORD_INPUT"),

  CHART_START_TO_GET_ORDER_BOOK: Symbol("CHART.START_TO_GET_ORDER_BOOK"),
  CHART_SUCCEEDED_TO_GET_ORDER_BOOK: Symbol("CHART.SUCCEEDED_TO_GET_ORDER_BOOK"),
  CHART_FAILED_TO_GET_ORDER_BOOK: Symbol("CHART.FAILED_TO_GET_ORDER_BOOK"),
  CHART_START_TO_GET_TICKERS: Symbol("CHART.START_TO_GET_TICKERS"),
  CHART_SUCCEEDED_TO_GET_TICKERS: Symbol("CHART.SUCCEEDED_TO_GET_TICKERS"),
  CHART_FAILED_TO_GET_TICKERS: Symbol("CHART.FAILED_TO_GET_TICKERS"),
  CHART_CHANGE_TITLE_CURRENCY: Symbol("CHART.CHANGE_TITLE_CURRENCY"),

  GLOBAL_LOCATION_CHANGE: "@@router/LOCATION_CHANGE",
};
